baseURL = 'https://kb.api-d.com/'
languageCode = 'fr-fr'
title = 'Jardin virtuel'

removePathAccents = true

[menu]
[[menu.main]]
name = "Domotique"
url = "/domotique/"
weight = 1
[[menu.main]]
name = "Informatique"
url = "/sysadm/"
weight = 2
[[menu.main]]
name = "Recherche"
weight = 3
params = {type = "search"}
[[menu.main]]
name = "GitHub"
weight = 4
url = "https://github.com/paris-ci/APID-KnowledgeBase"


[module]
[[module.imports]]
path = "github.com/imfing/hextra"

[params]
#  Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

[params.editURL]
enable = true
base = "https://github.com/paris-ci/APID-KnowledgeBase/edit/main/content"

# Optional parameters for each section
[params.domotique]
title = "Domotique"
description = "Articles, conseils et recommandations sur la domotique, la maison connectée et les objets connectés. Je suis un grand fan d'Homeassistant."

[params.sysadm]
title = "Administration Sytème"
description = "Articles et pense-bêtes sur l'administration système, la sécurité informatique et les réseaux."